audio:
  channels: 1
  device: null
  sample_rate: 16000
client:
  add_space: false
  auto_paste: false
  output_mode: clipboard
gui:
  show_popup: true
hotkeys:
  record:
    description: Начать/остановить запись
    keys: alt_gr
    mode: ptt
model:
  compute_type: float16
  device: cuda
  size: medium
server:
  host: localhost
  port: 8100
  reload: false
